export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  forgeModel: process.env.BUILT_IN_FORGE_MODEL ?? "",
  llmMode: process.env.LLM_MODE ?? "",
  llmTimeoutMs: process.env.LLM_TIMEOUT_MS ?? "",
  llmMaxRetries: process.env.LLM_MAX_RETRIES ?? "",
  llmMaxTokens: process.env.LLM_MAX_TOKENS ?? "",
};
